### ISSUE TITLE
Please add a license and a screen shot

### ISSUE THREAD

**Issue by unixorn** [Sokkam/small-terminal-diy-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Also, please add a license, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you pick one.

**Comment by Sokkam** [comment]
Thanks for your attention, this project was just created, the documentation is not yet complete, your suggestions will be a great help for improving my documentation, and also welcome to add my project to awesome-zsh-plugins.

**Comment by Sokkam** [comment]
> I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.
> 
> Also, please add a license, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you pick one.

Thanks for your attention, this project was just created, the documentation is not yet complete, your suggestions will be a great help for improving my documentation, and also welcome to add my project to awesome-zsh-plugins.

**Comment by unixorn** [comment]
Adding in https://github.com/unixorn/awesome-zsh-plugins/pull/692
